### ISSUE TITLE
Syntax highlight in readme.md

### ISSUE THREAD

**Issue by ElioenaiFerrari** [anu1097/golang-masking-tool#10]
**Describe the bug**
Is not a bug, is a improvement for documentation reading.

**Screenshots**
<img width="990" alt="Screenshot 2023-03-27 at 08 53 23" src="https://user-images.githubusercontent.com/51091121/227934138-0f4646c3-356d-4ab8-b54f-b15a99a9be63.png">
[Readme.md](https://github.com/anu1097/golang-masking-tool/files/11078222/Readme.md)

**Comment by anu1097** [comment]
I didn't get it honestly.

**Comment by yaronius** [comment]
@anu1097 I created a PR to fix that 🙂
