### ISSUE TITLE
using reflect.MakeSlice should adjust for Array case

### ISSUE THREAD

**Issue by andrey-tikhov** [anu1097/golang-masking-tool#13]
**Describe the bug**
Masking fails for uuid.UUID{} from "github.com/google/uuid"

**To Reproduce**
https://go.dev/play/p/cLHp_XmfGO3

`import (
	"fmt"

	mt "github.com/anu1097/golang-masking-tool"
	"github.com/anu1097/golang-masking-tool/filter"
	"github.com/google/uuid"
)

func main() {
	maskTool := mt.NewMaskTool(filter.FieldPrefixFilter("Password"))
	req := uuid.UUID{}

	fmt.Println(maskTool.MaskDetails(req))
}
`

**Expected behavior**
No panic

**Additional context**
well known bug already addressed for example in stretchr testify https://github.com/stretchr/testify/pull/1473/files

**Comment by anu1097** [comment]
Handled in https://github.com/anu1097/golang-masking-tool/pull/14
